package CampaignSettings;

public class Elements {

	public String _gotoDearOfficialArea = "//*[@id=\"email_div\"]/input";
	public String _kioskButton = "#xscroll > div.bubble-element.Group.baTaHww.bubble-r-container.flex.column > div.bubble-element.Group.baTaIaEl2.bubble-r-container.flex.column > div.bubble-element.Group.baTaIaEo2.bubble-r-container.flex.row > div.bubble-element.ionic-IonicToggle.clickable-element > label";
	//public String _sendEmailConfirmationMessage = "#inner > div.bubble-element.Group.baTaKcd2.bubble-r-container.flex.column > div.bubble-element.Alert.baUaBuaC1.bubble-r-vertical-center > div > div";
	public String _sendEmailConfirmationMessage = "//*[@id=\"inner\"]/div[6]/div[14]/div";
	public String _sendMeTextMessageCheckbox = "#redcheckbox > svg";
	public String _gotoDeliverySettingsTab = "#hscroll > div > div.clickable-element.bubble-element.Group.baTaHxz.bubble-r-container.fixed > div";
	public String _clickConstituentMailOnlyButton = "#xscroll > div.bubble-element.Group.baTaIaJaV2.bubble-r-container.flex.column > div.bubble-element.Group.baTaIaJaX2.bubble-r-container.flex.column > div.bubble-element.Group.baTaIaJaZ2.bubble-r-container.flex.row > div.bubble-element.ionic-IonicToggle.clickable-element > label";
	public String _constituentStateButton = "#input_state";
	public String _constituentStateButtonValue = "#input_state > option:nth-child(8)";
	public String _constituentSendingToDetails_Address1 = "//div[@class='clickable-element bubble-element Group baTqaMh8 bubble-r-container flex row']/div[@id='phone_targets']";
	public String _constituentSecondStateButtonValue = "#input_state > option:nth-child(3)";	
	public String _petitionStateButtonValue = "#input_state > option:nth-child(41)";
	public String _clickPetitionModeButton = "#xscroll > div.bubble-element.Group.baTaIaJaV2.bubble-r-container.flex.column > div.bubble-element.Group.baTaIaJc2.bubble-r-container.flex.column > div.bubble-element.Group.baTaIaJe2.bubble-r-container.flex.row > div.bubble-element.ionic-IonicToggle.clickable-element > label";
	public String _redirectAdvocatesButton = "#xscroll > div.bubble-element.Group.baTaIaJaV2.bubble-r-container.flex.column > div.bubble-element.Group.baTaIaJm2.bubble-r-container.flex.column > div.bubble-element.Group.baTaIaJo2.bubble-r-container.flex.row > div.bubble-element.ionic-IonicToggle.clickable-element > label";
	public String _redirectAdvocatesLinkTextArea = "#xscroll > div.bubble-element.Group.baTaIaJaV2.bubble-r-container.flex.column > div.bubble-element.Group.baTaRaPaP3.bubble-r-container.flex.column > input";	
	public String _verifySendersEmailButton = "#xscroll > div.bubble-element.Group.baTaIaJaV2.bubble-r-container.flex.column > div.bubble-element.Group.baTaIaJh2.bubble-r-container.flex.column > div.bubble-element.Group.baTaIaJj2.bubble-r-container.flex.row > div.bubble-element.ionic-IonicToggle.clickable-element > label";
	public String _confirmationEmailLink = "#xscroll > div.bubble-element.Group.baTaIaJaV2.bubble-r-container.flex.column > div.bubble-element.Group.baTaIaJh2.bubble-r-container.flex.column > div.bubble-element.Group.baTaRaPaD3.bubble-r-container.flex.column > input";
	public String _yesButton = "#save_changes_exit";
	public String _emailScreeningButton = "#xscroll > div.bubble-element.Group.baTaIaJaV2.bubble-r-container.flex.column > div.bubble-element.Group.baTmaFaQ3.bubble-r-container.flex.column > div.bubble-element.Group.baTmaFaS3.bubble-r-container.flex.row > div.bubble-element.ionic-IonicToggle.clickable-element > label";
	public String _sendEmailConfirmationMessageEmailScreening = "//*[@id=\"inner\"]/div[6]/div[14]/div";
	public String _gotoSocialShareSettings = "#hscroll > div > div.clickable-element.bubble-element.Group.baTaHyaC.bubble-r-container.fixed > div > div";
	public String _clickSendThankYouEmailCheckBox = "#xscroll > div.bubble-element.Group.baTaIbi0.bubble-r-container.flex.column > div.bubble-element.Group.baTaSaNl1.bubble-r-container.flex.column > div.bubble-element.Group.baTaSaNn1.bubble-r-container.flex.row > button > svg";
	public String _sendFromNameTextArea = "#xscroll > div.bubble-element.Group.baTaIbi0.bubble-r-container.flex.column > div.bubble-element.Group.baTaSaNl1.bubble-r-container.flex.column > div.bubble-element.Group.baTaSaNq1.bubble-r-container.flex.column > div.bubble-element.Group.baTaSaOaL1.bubble-r-container.flex.column > input";
	public String _sendFromEmailTextArea = "#xscroll > div.bubble-element.Group.baTaIbi0.bubble-r-container.flex.column > div.bubble-element.Group.baTaSaNl1.bubble-r-container.flex.column > div.bubble-element.Group.baTaSaNq1.bubble-r-container.flex.column > div.bubble-element.Group.baTaSaOaS1.bubble-r-container.flex.column > input";
	public String _emailSubjectTextArea = ".baTaSaOa1";
	public String _emailBody = "#email_body > form > div > div.tox-editor-container > div.tox-sidebar-wrap";
	public String _paragraphButton = "#email_body > form > div > div.tox-editor-container > div.tox-editor-header > div.tox-toolbar-overlord > div:nth-child(1) > div:nth-child(2) > button > span";
	public String _paragraphHeading1 = "//div[@title='Heading 1']";
	public String _fontStyle = "#email_body > form > div > div.tox-editor-container > div.tox-editor-header > div.tox-toolbar-overlord > div:nth-child(1) > div:nth-child(3) > button";
	public String _fontStyleValue1 = "//div[@title=' Impact']";
	public String _fontStyleValue2 = "//div[@title=' Courier New']";
	public String _fontSize = "#email_body > form > div > div.tox-editor-container > div.tox-editor-header > div.tox-toolbar-overlord > div:nth-child(1) > div:nth-child(4) > button";
	public String _fontSizeValue1 = "//div[@title='12pt']";
	public String _fontSizeValue2 = "//div[@title='36pt']";
	public String _linkToCampagin = "#xscroll > div.bubble-element.Group.baTaIbi0.bubble-r-container.flex.column > div.bubble-element.Group.baTaSaNl1.bubble-r-container.flex.column > div.bubble-element.Group.baTaSaNq1.bubble-r-container.flex.column > div.bubble-element.Group.baTaSaOh1.bubble-r-container.flex.column > button.clickable-element.bubble-element.Button.baTaSdaL1";
	public String _linkToInsertAdvocatesFirstName = "#xscroll > div.bubble-element.Group.baTaIbi0.bubble-r-container.flex.column > div.bubble-element.Group.baTaSaNl1.bubble-r-container.flex.column > div.bubble-element.Group.baTaSaNq1.bubble-r-container.flex.column > div.bubble-element.Group.baTaSaOh1.bubble-r-container.flex.column > button.clickable-element.bubble-element.Button.baTaSdaI1";
	public String _clickFlag = "//body[@id='tinymce']";
	public String _outlookEmail = "#i0116";
	public String _outlookPassword = "#i0118";
	public String _outlookNextOrSignInButton = "#idSIButton9";
	public String _outlookStaySignInYesNoButton = "#idBtn_Back";
	public String _newestEmail = "#AQAAAAAAAQABAAAAB5MqSQAAAAA\\= > div";
	public String __twitterShareTextArea = "#xscroll > div.bubble-element.Group.baTaIbi0.bubble-r-container.flex.column > div.bubble-element.Group.baTaIcaW0.bubble-r-container.flex.column > textarea";
	public String __twitterMentionTagTextArea = "#xscroll > div.bubble-element.Group.baTaIbi0.bubble-r-container.flex.column > div.bubble-element.Group.baTaIcaI0.bubble-r-container.flex.column > div.bubble-element.Group.baTaIcl0.bubble-r-container.flex.row > input";
	public String _twitterIcon = ".fa-twitter";
	public String _gotoThemeTab = "#menu-item > div.clickable-element.bubble-element.Group.baTaHaXaB0.bubble-r-container.flex.row > div.bubble-element.Text.baTaHaXaD0.bubble-r-vertical-center";
	public String _backGroundColor = "#bgpicker > div";	
	public String _backGroundColorValue = "body > div:nth-child(46) > div.sp-picker-container > div.sp-top.sp-cf > div.sp-top-inner > div.sp-hue > div";
	public String _colorCodeTextArea = "#g-content > div.bubble-element.Group.baTaIkaF.bubble-r-container.flex.row > div > div.bubble-element.Group.baTaIkaZ.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaFaF0.bubble-r-container.flex.row > div.bubble-element.Group.baTaJaEaX0.bubble-r-container.flex.column > input";
	public String _buttonColor = "#buttonpicker > div";	
	public String _colorCodeButtonTextArea = "#g-content > div.bubble-element.Group.baTaIkaF.bubble-r-container.flex.row > div > div.bubble-element.Group.baTaIkaZ.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaFaF0.bubble-r-container.flex.row > div.bubble-element.Group.baTaJaEj0.bubble-r-container.flex.column > input";
	public String _clickPreviewButton = "body > div.bubble-element.FloatingGroup.baTaIaFaP2.floating-group.bubble-r-container.flex.row > div.clickable-element.bubble-element.Group.baTaInaH.bubble-r-container.flex.row > div > div.clickable-element.bubble-element.Group.baTaInaE.bubble-r-container.fixed";
	public String _flag1 = "#email_div > div.bubble-element.Group.baTaJaQg0.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaQaZ0.bubble-r-container.flex.row > div.bubble-element.Group.baTnpaW10.bubble-r-container.flex.column > input";
	public String _flag2 = "#allow_company";
	public String _flag3 = "textarea.bubble-element";
	public String _fontColorButton= "#fontpicker > div";
	public String _fontColorTextArea= "#g-content > div.bubble-element.Group.baTaIkaF.bubble-r-container.flex.row > div > div.bubble-element.Group.baTaIkaZ.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaGaH0.bubble-r-container.flex.row > div.bubble-element.Group.baTaJaEu0.bubble-r-container.flex.column > input";
	public String __clickYesButton= "#save_changes_exit";
	public String _fontStyleButton= "#fontList";
	public String _fontStyleValue= "#fontList > option:nth-child(16)";
	public String _flag4 = "#email_div > div.bubble-element.Group.baTaJaQg0.bubble-r-container.flex.column > div.bubble-element.Group.baTaPrn3.bubble-r-container.flex.row > div.bubble-element.Group.baTnog10.bubble-r-container.flex.column > input";
	public String _previewCloseButton = "#sidemenu > div.bubble-element.Group.baTaJaOaT0.bubble-r-container.flex.row > div > button > svg > text";	
	public String _gotoDisplayTab= "#menu-item > div.clickable-element.bubble-element.Group.baTaHaWr0.bubble-r-container.flex.row > div.bubble-element.Text.baTaHaWt0.bubble-r-vertical-center > div";
	public String _advocatesActionTextArea= "#action_advocate";
	public String _clickWidgetCode= "#file_upload > div > div.bubble-element.Group.baTaJaIaD0.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaHo0.bubble-r-container.flex.column > textarea";
	public String __htmlEditor= "#textareawrapper > div > div.CodeMirror-scroll > div.CodeMirror-sizer > div";
	public String _runHTMLButton= "#runbtn";
	public String _clickFlag1= "#widget > div.bubble-element.Group.baTaOlaN4.bubble-r-container.flex.column";
	public String _clickShowProgressGoalCircle= "#file_upload > div > div.bubble-element.Group.baTaJaIaD0.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaHg0.bubble-r-container.flex.row > div.bubble-element.ionic-IonicToggle.clickable-element > label";
	public String _clickSaveButton= "#save_campaign";
	public String _clickCampaignHostagePage= "#file_upload > div > div.bubble-element.Group.baTaJaGaS0.bubble-r-container.flex.row > div.clickable-element.bubble-element.Group.baTaJaGaY0.bubble-r-container.fixed";
	public String _clickCampaignHostagePageLink= "#file_upload > div > div.bubble-element.Group.baTaJaIaM0.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaIaY0.bubble-r-container.flex.column > div.bubble-element.Text.baTaJaIaV0.clickable-element";
	public String _checkGoalCircle_ONorOFF= "//*[text()='0%']";
	public String _clickCampaignHostagePageLink2= "#file_upload > div > div.bubble-element.Group.baTaJaGaS0.bubble-r-container.flex.row > div.clickable-element.bubble-element.Group.baTaJaGaY0.bubble-r-container.fixed > div";
	public String _browseButton= "#file_upload > div > div.bubble-element.Group.baTaJaIaM0.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaKaR0.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaKk0.bubble-r-container.flex.row > div.bubble-element.Group.baTiaJaJ8.bubble-r-container.flex.row > button";
	public String _uploadButton= "#file_upload > div > div.bubble-element.Group.baTaJaIaM0.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaKaR0.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaKk0.bubble-r-container.flex.row > button";
	public String _searchTextArea= "#search-image-page";
	public String _clickImageBackgroundStyle= "#file_upload > div > div.bubble-element.Group.baTaJaIaM0.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaJb0.bubble-r-container.flex.column > div.bubble-element.RepeatingGroup.baTaJaJaB0.bubble-rg > div.bubble-element.group-item.bubble-r-container.flex.column.entry-2 > div > div.clickable-element.bubble-element.Group.baTaKpz5.bubble-r-container.flex.column > div > img";
	public String _clickCampaignWidgetTab= "#file_upload > div > div.bubble-element.Group.baTaJaGaS0.bubble-r-container.flex.row > div.clickable-element.bubble-element.Group.baTaJaGaU0.bubble-r-container.fixed > div";
	public String _clickImageHeaderStyle= "#file_upload > div > div.bubble-element.Group.baTaJaIaM0.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaJb0.bubble-r-container.flex.column > div.bubble-element.RepeatingGroup.baTaJaJaB0.bubble-rg > div.bubble-element.group-item.bubble-r-container.flex.column.entry-3 > div > div.clickable-element.bubble-element.Group.baTaKpz5.bubble-r-container.flex.column > div > img";
	public String _clickImageTopStyle= "#file_upload > div > div.bubble-element.Group.baTaJaIaM0.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaJb0.bubble-r-container.flex.column > div.bubble-element.RepeatingGroup.baTaJaJaB0.bubble-rg > div.bubble-element.group-item.bubble-r-container.flex.column.entry-4 > div > div.clickable-element.bubble-element.Group.baTaKpz5.bubble-r-container.flex.column > div > img";
	public String _clickImageCenterStyle= "#file_upload > div > div.bubble-element.Group.baTaJaIaM0.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaJb0.bubble-r-container.flex.column > div.bubble-element.RepeatingGroup.baTaJaJaB0.bubble-rg > div.bubble-element.group-item.bubble-r-container.flex.column.entry-5 > div > div.clickable-element.bubble-element.Group.baTaKpz5.bubble-r-container.flex.column > div > img";
	public String _clickImageBottomStyle= "div.group-item:nth-child(6) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1)";
	public String _showNumberActionsTaken= "#file_upload > div > div.bubble-element.Group.baTaJaIaM0.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaMd0.bubble-r-container.flex.row > div.bubble-element.ionic-IonicToggle.clickable-element > label";
	public String _checkingActionDetails= "//div[@class='bubble-element Group baTytaO5 bubble-r-container flex row']/div[@class='bubble-element Group baTytaN5 bubble-r-container flex row']/div/following-sibling::div";
	public String _inputCampaignPageTitle= "#file_upload > div > div.bubble-element.Group.baTaJaIaM0.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaKr0.bubble-r-container.flex.column > input";
	public String _inputCampaignPageBody= "#page_body";
	public String _clickBrowseFileLogoButton= "#browse_logo";
	public String _clickUploadImageButton= "#file_upload > div > div.bubble-element.Group.baTaJaIaM0.bubble-r-container.flex.column > div.bubble-element.Group.baTaSaYaL0.bubble-r-container.flex.column > div.bubble-element.Group.baTaSaZaJ0.bubble-r-container.flex.row > div.clickable-element.bubble-element.Group.baTaSaaE0.bubble-r-container.flex.row > div";
	public String _clickShowAccountLogoOnPageButton= "#file_upload > div > div.bubble-element.Group.baTaJaIaM0.bubble-r-container.flex.column > div.bubble-element.Group.baTaRaFaL6.bubble-r-container.flex.row > div > div > div.bubble-element.Group.baTaJaLj0.bubble-r-container.flex.row > div.bubble-element.ionic-IonicToggle.clickable-element > label";
	public String _accountLogo= "body > div.bubble-element.Page.baTaKaTaU3.bubble-r-container.flex.column.main-page > div.bubble-element.Group.baTaKbe0.bubble-r-container.flex.column > div.bubble-element.Group.baTaKaUaO3.bubble-r-container.flex.row > div.bubble-element.Group.baTaKaYu3.bubble-r-container.flex.column > div.bubble-element.Image.baUaAqv > img";
	public String _gotoTargetsTab= "#menu-item > div.clickable-element.bubble-element.Group.baTaHaWw0.bubble-r-container.flex.row > div.bubble-element.Text.baTaHaWy0.bubble-r-vertical-center";
	
	public String _selectAllButton= "#g-content > div.bubble-element.Group.baTaIlaW1.bubble-r-container.flex.column > div > div.bubble-element.Group.baTaJaFaK1.bubble-r-container.flex.row > div.bubble-element.Group.baTaLoaW4.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaFb1.bubble-r-container.flex.row > div.bubble-element.Group.baTaLok4.bubble-r-container.flex.row > div.clickable-element.bubble-element.Group.baTaLop4.bubble-r-container.flex.row > button > svg > text";
	public String _clickSelectAddSelectedButton= "#add_targets > div";
	public String _viewAddedTargets= "body > div.bubble-element.FloatingGroup.baTaIaFaP2.floating-group.bubble-r-container.flex.row > div.clickable-element.bubble-element.Group.baTaInaH.bubble-r-container.flex.row > div > div.clickable-element.bubble-element.Group.baTaNaGaX3.bubble-r-container.flex.row > div.bubble-element.Text.baTaNaGaZ3.bubble-r-vertical-center > div";
	public String _X_removeButton= "#rg-target > div.clickable-element.bubble-element.Group.baTaNaKaV3.bubble-r-container.flex.column > div";
	public String _removeALLButton= "#selectedtarget > div.bubble-element.Group.baTaNaHaT3.bubble-r-container.flex.row > div.bubble-element.Group.baTaNaHw3.bubble-r-container.flex.row > div > div";
	public String _statesTab= "#xscroll > div > div.bubble-element.Text.baTaJaGaM1.bubble-r-vertical-center.clickable-element > div";
	public String _selectStateTextArea= "body > div.bubble-element.Popup.baTjaBi1.bubble-r-container.flex.column > div.bubble-element.Group.baTjaBr1.bubble-r-container.flex.column > div.bubble-element.Group.baTjaBv1.bubble-r-container.flex.column > div.bubble-element.select2-MultiDropdown > span > span.selection > span > ul > li > input";
	public String _selectStateTextArea_Value= "//*[@id=\"select2-wgzx-results\"]/li[3]";
	public String _addStatesButton= "body > div.bubble-element.Popup.baTjaBi1.bubble-r-container.flex.column > div.bubble-element.Group.baTjaBr1.bubble-r-container.flex.column > div.bubble-element.Group.baTjaBs1.bubble-r-container.fixed > button";
	public String _selectCountryState= "#g-content > div.bubble-element.Group.baTaIlaW1.bubble-r-container.flex.column > div > div.bubble-element.Group.baTaJaFaK1.bubble-r-container.flex.row > div.clickable-element.bubble-element.Group.baTaJaFaL1.bubble-r-container.flex.column > div.bubble-element.Group.baTaJaFaW1.bubble-r-container.flex.column > div.bubble-element.RepeatingGroup.baTaJaFaZ1.bubble-rg > div.bubble-element.group-item.bubble-r-container.flex.column.entry-1 > div > button > svg > text";
	public String _state_Governor= "#g-content > div.bubble-element.Group.baTaIlaW1.bubble-r-container.flex.column > div > div.bubble-element.Group.baTaJaFaK1.bubble-r-container.flex.row > div.clickable-element.bubble-element.Group.baTaJaFaL1.bubble-r-container.flex.column > div.bubble-element.Group.baTwaFaQ0.bubble-r-container.flex.column > div.clickable-element.bubble-element.Group.baTvaZaD.bubble-r-container.flex.row > button > svg > text";
	public String _state_House= "#g-content > div.bubble-element.Group.baTaIlaW1.bubble-r-container.flex.column > div > div.bubble-element.Group.baTaJaFaK1.bubble-r-container.flex.row > div.clickable-element.bubble-element.Group.baTaJaFaL1.bubble-r-container.flex.column > div.bubble-element.Group.baTwaFaQ0.bubble-r-container.flex.column > div.clickable-element.bubble-element.Group.baTwaFaK0.bubble-r-container.flex.row > button";
	public String _state_Senate= "#g-content > div.bubble-element.Group.baTaIlaW1.bubble-r-container.flex.column > div > div.bubble-element.Group.baTaJaFaK1.bubble-r-container.flex.row > div.clickable-element.bubble-element.Group.baTaJaFaL1.bubble-r-container.flex.column > div.bubble-element.Group.baTwaFaQ0.bubble-r-container.flex.column > div.clickable-element.bubble-element.Group.baTwaFaY0.bubble-r-container.flex.row > button";
	public String _customTargetsTab= "#xscroll > div > div.bubble-element.Text.baTaJaFaJ1.clickable-element.bubble-r-vertical-center > div";
	public String _X_removeButtonCustomTargets= "#rg-target > div.clickable-element.bubble-element.Group.baTaRzz6.bubble-r-container.flex.column > div";
	public String _local= "#g-content > div.bubble-element.Group.baTaIlaW1.bubble-r-container.flex.column > div > div.bubble-element.Group.baTaJaFaK1.bubble-r-container.flex.row > div.clickable-element.bubble-element.Group.baTaJaFaL1.bubble-r-container.flex.column > div.bubble-element.Group.baTaPaEaI9.bubble-r-container.flex.column > div.bubble-element.RepeatingGroup.baTaPaEaL9.bubble-rg > div.bubble-element.group-item.bubble-r-container.flex.row.entry-1 > div > button > svg > text";
	public String _state= "#g-content > div.bubble-element.Group.baTaIlaW1.bubble-r-container.flex.column > div > div.bubble-element.Group.baTaJaFaK1.bubble-r-container.flex.row > div.clickable-element.bubble-element.Group.baTaJaFaL1.bubble-r-container.flex.column > div.bubble-element.Group.baTaPaEaI9.bubble-r-container.flex.column > div.bubble-element.RepeatingGroup.baTaPaEaL9.bubble-rg > div.bubble-element.group-item.bubble-r-container.flex.row.entry-2 > div > button > svg > text";
	public String _national= "#g-content > div.bubble-element.Group.baTaIlaW1.bubble-r-container.flex.column > div > div.bubble-element.Group.baTaJaFaK1.bubble-r-container.flex.row > div.clickable-element.bubble-element.Group.baTaJaFaL1.bubble-r-container.flex.column > div.bubble-element.Group.baTaPaEaI9.bubble-r-container.flex.column > div.bubble-element.RepeatingGroup.baTaPaEaL9.bubble-rg > div.bubble-element.group-item.bubble-r-container.flex.row.entry-3 > div > button > svg > text";
	public String _manageCustomTargets= "#x-scroll > div.clickable-element.bubble-element.Group.baTaPaBk9.bubble-r-container.flex.row > div.bubble-element.Text.baTaPaBa9.bubble-r-vertical-center > div";
	public String _createButton= "#g-content > div.bubble-element.Group.baTaIlaW1.bubble-r-container.flex.column > div > div.bubble-element.Group.baTaPaHaX0.bubble-r-container.flex.row > div.clickable-element.bubble-element.Group.baTaPaHi0.bubble-r-container.flex.row > div";
	public String _creationCity= "body > div.bubble-element.CustomElement.baTaPaLa0.bubble-r-container.flex.column > div.bubble-element.Group.baTaPaIi0.bubble-r-container.flex.column > div.bubble-element.Group.baTaPaJaJ0.bubble-r-container.flex.row > input";
	public String _creationState= "body > div.bubble-element.CustomElement.baTaPaLa0.bubble-r-container.flex.column > div.bubble-element.Group.baTaPaIi0.bubble-r-container.flex.column > div.clickable-element.bubble-element.Group.baTaPaJaQ0.bubble-r-container.flex.row > select > option:nth-child(41)";
	public String _creationName= "body > div.bubble-element.CustomElement.baTaPaLa0.bubble-r-container.flex.column > div.bubble-element.Group.baTaPaIi0.bubble-r-container.flex.column > div.bubble-element.Group.baTaPaJa0.bubble-r-container.flex.row > input";
	public String _creationEmail= "body > div.bubble-element.CustomElement.baTaPaLa0.bubble-r-container.flex.column > div.bubble-element.Group.baTaPaIi0.bubble-r-container.flex.column > div.bubble-element.Group.baTaPaJu0.bubble-r-container.flex.row > input";
	public String _creationPhone= "body > div.bubble-element.CustomElement.baTaPaLa0.bubble-r-container.flex.column > div.bubble-element.Group.baTaPaIi0.bubble-r-container.flex.column > div.bubble-element.Group.baTaPaJp0.bubble-r-container.flex.row > input";
	public String _creationPosition= "body > div.bubble-element.CustomElement.baTaPaLa0.bubble-r-container.flex.column > div.bubble-element.Group.baTaPaIi0.bubble-r-container.flex.column > div.bubble-element.Group.baTaPaJf0.bubble-r-container.flex.row > input";
	public String _customCreateButton= "body > div.bubble-element.CustomElement.baTaPaLa0.bubble-r-container.flex.column > div.bubble-element.Group.baTaPaIaV0.bubble-r-container.flex.row > button";
	public String _creationConstituency= "body > div.bubble-element.CustomElement.baTaPaLa0.bubble-r-container.flex.column > div.bubble-element.Group.baTaPaIi0.bubble-r-container.flex.column > div.bubble-element.Group.baTaPaJaE0.bubble-r-container.flex.row > select > option:nth-child(2)";
	public String _bulkUploadCustomTargets= "#g-content > div.bubble-element.Group.baTaIlaW1.bubble-r-container.flex.column > div > div.bubble-element.Group.baTaPaHaX0.bubble-r-container.flex.row > div.clickable-element.bubble-element.Group.baTaPaHn0.bubble-r-container.fixed > div > div.bubble-element.Text.baTaPaHq0";
	public String _browseFile= "#bulkcustom";
	public String _targets_SearhArea= "#search-target";
	public String _searchButton= "#g-content > div.bubble-element.Group.baTaIlaW1.bubble-r-container.flex.column > div > div.bubble-element.Group.baTaJaFq1.bubble-r-container.flex.row > div.bubble-element.Group.baTaJaFr1.bubble-r-container.flex.row > div > div";




}
